#!/usr/bin/env bash
# Tests for lib/evidence.sh
#
# Run: bash lib/evidence.test.sh
#
# Strategy: a throwaway State dir and PR bodies in temp files. The cases are
# the sink's promises: the round's artifacts land outside any checkout, a
# screenshot name sorts into reading order or is refused, and a second round
# REFRESHES the `## Screenshots` section instead of stacking a new copy under
# the old one.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB="${SCRIPT_DIR}/evidence.sh"

TESTS_RUN=0; TESTS_FAILED=0; FAILED_NAMES=()
pass() { TESTS_RUN=$((TESTS_RUN + 1)); echo "  PASS: $1"; }
fail() { TESTS_RUN=$((TESTS_RUN + 1)); TESTS_FAILED=$((TESTS_FAILED + 1)); FAILED_NAMES+=("$1"); echo "  FAIL: $1"; [ -n "${2:-}" ] && echo "    $2"; }

export AUTO_AGENT_HOST_ENV=/nonexistent/host-env
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT
export AUTO_AGENT_STATE_DIR="${WORK}/state"

run() { bash "${LIB}" "$@"; }

echo "TEST: the round's artifact directory is one timestamped dir per round, under the State dir"
dir="$(EVIDENCE_NOW=20260922T101500Z run dir --pr 77)"
if [ "${dir}" = "${AUTO_AGENT_STATE_DIR}/verify/pr-77/20260922T101500Z" ] && [ -d "${dir}" ]; then pass "dir: named and created"; else fail "dir: named and created" "got: ${dir}"; fi

echo "TEST: a re-verify round gets its own directory, keyed to the round number"
dir2="$(EVIDENCE_NOW=20260922T101500Z run dir --pr 77 --round 2)"
if [ "${dir2}" = "${dir}-r2" ] && [ -d "${dir2}" ]; then pass "dir: per round"; else fail "dir: per round" "got: ${dir2}"; fi

echo "TEST: dir refuses a PR that is not a number"
run dir --pr abc >/dev/null 2>&1; [ $? -eq 2 ] && pass "dir: usage" || fail "dir: usage"
run dir >/dev/null 2>&1; [ $? -eq 2 ] && pass "dir: --pr is required" || fail "dir: --pr is required"

echo "TEST: a screenshot name is <surface>-NN-<slug>.png, zero-padded into reading order"
if [ "$(run name web 1 home-page)" = "web-01-home-page.png" ]; then pass "name: padded"; else fail "name: padded" "got: $(run name web 1 home-page)"; fi
if [ "$(run name panel 12 smoke-screen)" = "panel-12-smoke-screen.png" ]; then pass "name: two digits"; else fail "name: two digits"; fi
if [ "$(run name web 08 late)" = "web-08-late.png" ]; then pass "name: a padded index is not read as octal"; else fail "name: a padded index is not read as octal" "got: $(run name web 08 late)"; fi

echo "TEST: a name that would not sort, or not read as a caption, is refused"
run name web x home >/dev/null 2>&1; [ $? -eq 1 ] && pass "name: index must be a number" || fail "name: index must be a number"
run name web 1 'Home Page' >/dev/null 2>&1; [ $? -eq 1 ] && pass "name: slug must be a slug" || fail "name: slug must be a slug"
run name 'Web UI' 1 home >/dev/null 2>&1; [ $? -eq 1 ] && pass "name: surface must be a Surface name" || fail "name: surface must be a Surface name"

echo "TEST: shots lists the tour in reading order, with a caption read out of the name"
: > "${dir}/web-02-item-list.png"
: > "${dir}/web-01-home-page.png"
: > "${dir}/notes.txt"
out="$(run shots "${dir}")"
want="web — home page	${dir}/web-01-home-page.png
web — item list	${dir}/web-02-item-list.png"
if [ "${out}" = "${want}" ]; then pass "shots: order and captions"; else fail "shots: order and captions" "got: ${out}"; fi
run shots "${WORK}/nope" >/dev/null 2>&1; [ $? -eq 2 ] && pass "shots: missing directory" || fail "shots: missing directory"

BODY="${WORK}/body.md"
cat > "${BODY}" <<'MD'
Closes #12

## Summary

What this does.

## Manual verification

- [ ] the item list shows every posted item

---

Generated by something.
MD

echo "TEST: inject puts the tour before the checklist it belongs to"
out="$(printf 'web — home page\thttps://example.test/a.png\n' | run inject "${BODY}")"
if printf '%s' "${out}" | grep -q '^## Screenshots$' &&
   [ "$(printf '%s' "${out}" | grep -n '^## Screenshots$' | cut -d: -f1)" -lt "$(printf '%s' "${out}" | grep -n '^## Manual verification$' | cut -d: -f1)" ]; then
    pass "inject: before the checklist"
else fail "inject: before the checklist" "got: ${out}"; fi
if printf '%s' "${out}" | grep -q '!\[web — home page\](https://example.test/a.png)'; then pass "inject: a URL is an image"; else fail "inject: a URL is an image" "got: ${out}"; fi

echo "TEST: a Host with no image uploader still gets a tour that says where the pixels are"
out="$(printf 'web — home page\t%s/web-01-home-page.png\n' "${dir}" | run inject "${BODY}")"
if printf '%s' "${out}" | grep -q "\`${dir}/web-01-home-page.png\` — on the Host"; then pass "inject: a path is cited"; else fail "inject: a path is cited" "got: ${out}"; fi

echo "TEST: a second round refreshes the section instead of stacking a new copy"
printf 'web — home page\thttps://example.test/a.png\n' | run inject "${BODY}" > "${WORK}/round1.md"
printf 'web — home page\thttps://example.test/b.png\n' | run inject "${WORK}/round1.md" > "${WORK}/round2.md"
if [ "$(grep -c '^## Screenshots$' "${WORK}/round2.md")" = "1" ] &&
   grep -q 'b\.png' "${WORK}/round2.md" && ! grep -q 'a\.png' "${WORK}/round2.md"; then
    pass "inject: idempotent refresh"
else fail "inject: idempotent refresh" "$(cat "${WORK}/round2.md")"; fi

echo "TEST: the rest of the body survives a round byte for byte"
if grep -q '^What this does\.$' "${WORK}/round2.md" && grep -q '^- \[ \] the item list shows every posted item$' "${WORK}/round2.md" &&
   grep -q '^Generated by something\.$' "${WORK}/round2.md"; then pass "inject: the body is preserved"; else fail "inject: the body is preserved"; fi

echo "TEST: a round that captured nothing never destroys what an earlier round posted"
printf '' | run inject "${WORK}/round2.md" > "${WORK}/round3.md"
if diff -q "${WORK}/round2.md" "${WORK}/round3.md" >/dev/null; then pass "inject: empty input is a no-op"; else fail "inject: empty input is a no-op" "$(diff "${WORK}/round2.md" "${WORK}/round3.md")"; fi

echo "TEST: a Screenshots section a human wrote, with no marker, is left alone"
cat > "${WORK}/human.md" <<'MD'
## Screenshots

A human's own words and their own image.

## Manual verification

- [ ] something
MD
out="$(printf 'web — home\thttps://example.test/c.png\n' | run inject "${WORK}/human.md")"
if printf '%s' "${out}" | grep -q "A human's own words"; then pass "inject: a hand-written section survives"; else fail "inject: a hand-written section survives" "got: ${out}"; fi

echo "TEST: a body with no checklist and no rule gets the section appended"
printf 'Just a sentence.\n' > "${WORK}/bare.md"
out="$(printf 'web — home\thttps://example.test/c.png\n' | run inject "${WORK}/bare.md")"
if printf '%s' "${out}" | head -1 | grep -q 'Just a sentence\.' && printf '%s' "${out}" | grep -q '^## Screenshots$'; then pass "inject: appended"; else fail "inject: appended" "got: ${out}"; fi

echo "TEST: inject refuses a body file that is not there"
run inject "${WORK}/nope.md" >/dev/null 2>&1; [ $? -eq 2 ] && pass "inject: missing body" || fail "inject: missing body"
run bogus >/dev/null 2>&1; [ $? -eq 2 ] && pass "usage: unknown subcommand" || fail "usage: unknown subcommand"

echo ""
echo "Tests run: ${TESTS_RUN}, failed: ${TESTS_FAILED}"
if [ "${TESTS_FAILED}" -gt 0 ]; then printf '  - %s\n' "${FAILED_NAMES[@]}"; exit 1; fi
exit 0
